function createfigure(X1, Y1, Z1, S1, C1, X2, Y2, Z2, C2)
%CREATEFIGURE(X1,Y1,Z1,S1,C1,X2,Y2,Z2,C2)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c
%  X2:  scatter3 x
%  Y2:  scatter3 y
%  Z2:  scatter3 z
%  C2:  scatter3 c

%  Auto-generated by MATLAB on 27-Feb-2014 13:09:27

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
view(axes1,[-101.5 14]);
grid(axes1,'on');
hold(axes1,'all');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'Parent',axes1,'DisplayName','non-resovior');

% Create scatter3
scatter3(X2,Y2,Z2,S1,C2,'Parent',axes1,'DisplayName','resovior');

% Create legend
legend(axes1,'show');

