function createfigure(X1, Y1)
%CREATEFIGURE(X1,Y1)
%  X1:  vector of x data
%  Y1:  vector of y data

%  Auto-generated by MATLAB on 17-Feb-2014 14:20:38

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-2.91667493474156 2.88765329359986]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[-0.0454080456502227 0.560101839898273]);
view(axes1,[90 90]);
box(axes1,'on');
hold(axes1,'all');

% Create plot
plot(X1,Y1);

% Create xlabel
xlabel('{z}','VerticalAlignment','bottom','Rotation',90,...
    'HorizontalAlignment','center');

% Create title
title('({256} {z}^{2} + {64})/({1024} {z}^{2}) - ({256} {z}^{8} - {256} {z}^{6} + {96} {z}^{4} - {16} {z}^{2} + {1})/({1024} {z}^{2} (({z} - {1}/{2})^{2})^{{3}/{2}} (({z} + {1}/{2})^{2})^{{3}/{2}})');

